<script setup lang="ts">
// Multi-variant icon. `default` is the original silhouette; `alt` is the
// pqoqubbw/lucide-animated silhouette. Element graphs differ across variants
// (different tags or counts), so we delegate to `<MultiVariantIcon>` rather
// than the standard hand-templated layout.
//
// Generated by scripts/port-pqoqubbw-icons.mjs (multi-variant merge path).
// Hand-edits survive port reruns — the script preserves SFCs that already
// host an `alt` variant via this path.
import { computed } from 'vue'
import type { Variants } from 'motion-v'
import AnimateIcon from '../core/AnimateIcon.vue'
import MultiVariantIcon from '../core/MultiVariantIcon.vue'
import { hasOwnTriggers, type IconTriggerProps } from '../core/context'
import type { MultiVariantAnimations } from '../core/element-types'

const props = withDefaults(
  defineProps<IconTriggerProps & { strokeWidth?: number }>(),
  { size: 28, strokeWidth: 2 },
)

const animations: MultiVariantAnimations = {
  default: {
    elements: [
      { tag: "circle", attrs: { cx: "12", cy: "12", r: "4" }, key: "circle" },
      { tag: "line", attrs: { x1: "12", y1: "4", x2: "12", y2: "2" }, key: "line1" },
      { tag: "line", attrs: { x1: "17.7", y1: "6.3", x2: "19.1", y2: "4.9" }, key: "line2" },
      { tag: "line", attrs: { x1: "20", y1: "12", x2: "22", y2: "12" }, key: "line3" },
      { tag: "line", attrs: { x1: "17.7", y1: "17.7", x2: "19.1", y2: "19.1" }, key: "line4" },
      { tag: "line", attrs: { x1: "12", y1: "20", x2: "12", y2: "22" }, key: "line5" },
      { tag: "line", attrs: { x1: "6.3", y1: "17.7", x2: "4.9", y2: "19.1" }, key: "line6" },
      { tag: "line", attrs: { x1: "4", y1: "12", x2: "2", y2: "12" }, key: "line7" },
      { tag: "line", attrs: { x1: "6.3", y1: "6.3", x2: "4.9", y2: "4.9" }, key: "line8" },
    ],
    variants: (() => {
    const animation: Record<string, Variants> = {
      circle: {},
    };

    for (let i = 1; i <= 8; i++) {
      animation[`line${i}`] = {
        initial: { opacity: 1, scale: 1 },
        animate: {
          opacity: [0, 1],
          pathLength: [0, 1],
          transition: {
            duration: 0.6,
            ease: 'easeInOut',
            delay: (i - 1) * 0.15,
          },
        },
      };
    }

    return animation;
  })() as Record<string, Variants>,
  },
  alt: {
    elements: [
      { tag: "circle", attrs: { cx: "12", cy: "12", r: "4" } },
      { tag: "path", attrs: { "v-for": "(d, index) in VFOR_LIST_1" }, key: "path" },
    ],
    variants: {
    path: {
  initial: { opacity: 1 },
  animate: (i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }),
},
  } as Record<string, Variants>,
  },
}

const selfWrap = computed(() => hasOwnTriggers(props))
</script>

<template>
  <AnimateIcon
    v-if="selfWrap"
    :animate="props.animate"
    :animateOnHover="props.animateOnHover"
    :animateOnTap="props.animateOnTap"
    :animateOnView="props.animateOnView"
    :animation="props.animation"
    :persistOnAnimateEnd="props.persistOnAnimateEnd"
    :initialOnAnimateEnd="props.initialOnAnimateEnd"
    :clip="props.clip"
    :triggerTarget="props.triggerTarget"
  >
    <Sun :size="props.size" :strokeWidth="props.strokeWidth" />
  </AnimateIcon>

  <MultiVariantIcon
    v-else
    :animations="animations"
    :size="props.size"
    :strokeWidth="props.strokeWidth"
  />
</template>
